import { LightingPreset, LightingSettings, MaterialPreset, MaterialSettings } from '../types/studio';

export const MATERIAL_PRESETS: MaterialPreset[] = [
  {
    id: 'brushed_titanium',
    name: 'Fırçalanmış Titanyum',
    category: 'Metal',
    swatchGradient: 'linear-gradient(135deg, #cbd5e1 0%, #64748b 50%, #334155 100%)',
    settings: {
      color: '#B8C2CC',
      roughness: 0.28,
      metalness: 0.92,
      clearcoat: 0.15,
      clearcoatRoughness: 0.25,
      ior: 1.5,
      transmission: 0,
      opacity: 1,
      emissiveColor: '#000000',
      emissiveIntensity: 0,
      flatShading: false,
      doubleSided: true,
      surfacePattern: 'brushed_metal',
      patternScale: 4,
      bumpScale: 0.025,
    },
  },
  {
    id: 'anodized_gold',
    name: 'Anodize Altın',
    category: 'Metal',
    swatchGradient: 'linear-gradient(135deg, #fde68a 0%, #f59e0b 55%, #92400e 100%)',
    settings: {
      color: '#E5A93C',
      roughness: 0.2,
      metalness: 0.96,
      clearcoat: 0.3,
      clearcoatRoughness: 0.12,
      ior: 1.6,
      transmission: 0,
      opacity: 1,
      emissiveColor: '#000000',
      emissiveIntensity: 0,
      flatShading: false,
      doubleSided: true,
      surfacePattern: 'none',
      patternScale: 4,
      bumpScale: 0.015,
    },
  },
  {
    id: 'matte_ceramic',
    name: 'Mat Porselen Seramik',
    category: 'Seramik',
    swatchGradient: 'linear-gradient(135deg, #f8fafc 0%, #e2e8f0 60%, #94a3b8 100%)',
    settings: {
      color: '#EAECEF',
      roughness: 0.42,
      metalness: 0.04,
      clearcoat: 0.65,
      clearcoatRoughness: 0.18,
      ior: 1.55,
      transmission: 0,
      opacity: 1,
      emissiveColor: '#000000',
      emissiveIntensity: 0,
      flatShading: false,
      doubleSided: true,
      surfacePattern: 'micro_sand',
      patternScale: 5,
      bumpScale: 0.01,
    },
  },
  {
    id: 'automotive_carbon',
    name: 'Karbon Fiber Kompozit',
    category: 'Kompozit',
    swatchGradient: 'linear-gradient(135deg, #475569 0%, #1e293b 50%, #0f172a 100%)',
    settings: {
      color: '#262B33',
      roughness: 0.24,
      metalness: 0.45,
      clearcoat: 0.92,
      clearcoatRoughness: 0.08,
      ior: 1.58,
      transmission: 0,
      opacity: 1,
      emissiveColor: '#000000',
      emissiveIntensity: 0,
      flatShading: false,
      doubleSided: true,
      surfacePattern: 'carbon_weave',
      patternScale: 6,
      bumpScale: 0.04,
    },
  },
  {
    id: 'sla_resin_amber',
    name: 'Mühendislik Reçinesi (SLA)',
    category: '3B Baskı',
    swatchGradient: 'linear-gradient(135deg, #38bdf8 0%, #0284c7 60%, #0c4a6e 100%)',
    settings: {
      color: '#2294E3',
      roughness: 0.32,
      metalness: 0.08,
      clearcoat: 0.55,
      clearcoatRoughness: 0.22,
      ior: 1.52,
      transmission: 0.25,
      opacity: 0.95,
      emissiveColor: '#042f4a',
      emissiveIntensity: 0.12,
      flatShading: false,
      doubleSided: true,
      surfacePattern: 'print_layers',
      patternScale: 7,
      bumpScale: 0.02,
    },
  },
  {
    id: 'copper_alloy',
    name: 'Saten Bakır Alaşım',
    category: 'Metal',
    swatchGradient: 'linear-gradient(135deg, #fdba74 0%, #ea580c 55%, #7c2d12 100%)',
    settings: {
      color: '#D9734E',
      roughness: 0.26,
      metalness: 0.94,
      clearcoat: 0.2,
      clearcoatRoughness: 0.2,
      ior: 1.5,
      transmission: 0,
      opacity: 1,
      emissiveColor: '#000000',
      emissiveIntensity: 0,
      flatShading: false,
      doubleSided: true,
      surfacePattern: 'brushed_metal',
      patternScale: 5,
      bumpScale: 0.02,
    },
  },
  {
    id: 'frosted_quartz',
    name: 'Buzlu Kuvars Cam',
    category: 'Cam',
    swatchGradient: 'linear-gradient(135deg, #e0f2fe 0%, #7dd3fc 50%, #0369a1 100%)',
    settings: {
      color: '#D8F3FF',
      roughness: 0.14,
      metalness: 0.02,
      clearcoat: 1.0,
      clearcoatRoughness: 0.05,
      ior: 1.52,
      transmission: 0.78,
      opacity: 0.86,
      emissiveColor: '#082f49',
      emissiveIntensity: 0.08,
      flatShading: false,
      doubleSided: true,
      surfacePattern: 'none',
      patternScale: 4,
      bumpScale: 0,
    },
  },
  {
    id: 'pla_terracotta',
    name: 'FDM Mat Filament (PLA)',
    category: '3B Baskı',
    swatchGradient: 'linear-gradient(135deg, #fca5a5 0%, #ef4444 55%, #991b1b 100%)',
    settings: {
      color: '#E0533C',
      roughness: 0.68,
      metalness: 0.02,
      clearcoat: 0.08,
      clearcoatRoughness: 0.5,
      ior: 1.46,
      transmission: 0,
      opacity: 1,
      emissiveColor: '#000000',
      emissiveIntensity: 0,
      flatShading: false,
      doubleSided: true,
      surfacePattern: 'print_layers',
      patternScale: 8,
      bumpScale: 0.045,
    },
  },
];

export const DEFAULT_MATERIAL_SETTINGS: MaterialSettings = {
  useOriginalMaterials: true,
  presetId: 'original',
  wireframe: false,
  ...MATERIAL_PRESETS[0].settings,
};

export const LIGHTING_PRESETS: LightingPreset[] = [
  {
    id: 'studio_three_point',
    name: 'Üç Noktalı Ürün Stüdyosu',
    description: 'Dengeli ana ışık, soğuk dolgu ve keskin kontur aydınlatması',
    settings: {
      keyLight: {
        enabled: true,
        color: '#FFF7ED',
        intensity: 2.8,
        azimuth: 42,
        elevation: 48,
        distance: 7,
        castShadow: true,
      },
      fillLight: {
        enabled: true,
        color: '#93C5FD',
        intensity: 1.35,
        azimuth: -55,
        elevation: 28,
        distance: 7,
      },
      rimLight: {
        enabled: true,
        color: '#FDE68A',
        intensity: 2.4,
        azimuth: -155,
        elevation: 52,
        distance: 7,
      },
      ambientIntensity: 0.45,
      ambientColor: '#E2E8F0',
      envIntensity: 1.15,
      exposure: 1.1,
      backgroundColor: '#0B0D11',
    },
  },
  {
    id: 'golden_hour',
    name: 'Sıcak Altın Saat',
    description: 'Kehribar ana ışık ve derin atmosferik kontrast',
    settings: {
      keyLight: {
        enabled: true,
        color: '#FDBA74',
        intensity: 3.4,
        azimuth: 65,
        elevation: 24,
        distance: 7,
        castShadow: true,
      },
      fillLight: {
        enabled: true,
        color: '#6366F1',
        intensity: 0.9,
        azimuth: -70,
        elevation: 35,
        distance: 7,
      },
      rimLight: {
        enabled: true,
        color: '#FEF08A',
        intensity: 3.1,
        azimuth: -130,
        elevation: 30,
        distance: 7,
      },
      ambientIntensity: 0.35,
      ambientColor: '#FED7AA',
      envIntensity: 1.0,
      exposure: 1.15,
      backgroundColor: '#12100E',
    },
  },
  {
    id: 'technical_lab',
    name: 'Endüstriyel CAD Laboratuvarı',
    description: 'Yüksek netlikli nötr beyaz mühendislik inceleme ışığı',
    settings: {
      keyLight: {
        enabled: true,
        color: '#FFFFFF',
        intensity: 2.6,
        azimuth: 35,
        elevation: 60,
        distance: 7,
        castShadow: true,
      },
      fillLight: {
        enabled: true,
        color: '#E0F2FE',
        intensity: 1.8,
        azimuth: -45,
        elevation: 45,
        distance: 7,
      },
      rimLight: {
        enabled: true,
        color: '#38BDF8',
        intensity: 2.2,
        azimuth: 170,
        elevation: 50,
        distance: 7,
      },
      ambientIntensity: 0.65,
      ambientColor: '#F8FAFC',
      envIntensity: 1.4,
      exposure: 1.2,
      backgroundColor: '#0F141C',
    },
  },
  {
    id: 'dramatic_rim',
    name: 'Dramatik Kontur & Silüet',
    description: 'Düşük dolgu ışığı ve keskin kenar vurguları',
    settings: {
      keyLight: {
        enabled: true,
        color: '#F8FAFC',
        intensity: 2.1,
        azimuth: 25,
        elevation: 35,
        distance: 7,
        castShadow: true,
      },
      fillLight: {
        enabled: true,
        color: '#334155',
        intensity: 0.4,
        azimuth: -60,
        elevation: 20,
        distance: 7,
      },
      rimLight: {
        enabled: true,
        color: '#F59E0B',
        intensity: 4.2,
        azimuth: -165,
        elevation: 42,
        distance: 7,
      },
      ambientIntensity: 0.2,
      ambientColor: '#94A3B8',
      envIntensity: 0.85,
      exposure: 1.0,
      backgroundColor: '#07080A',
    },
  },
];

export const DEFAULT_LIGHTING_SETTINGS: LightingSettings = {
  presetId: 'studio_three_point',
  keyLight: {
    enabled: true,
    color: '#FFF7ED',
    intensity: 2.8,
    azimuth: 42,
    elevation: 48,
    distance: 7,
    castShadow: true,
  },
  fillLight: {
    enabled: true,
    color: '#93C5FD',
    intensity: 1.35,
    azimuth: -55,
    elevation: 28,
    distance: 7,
  },
  rimLight: {
    enabled: true,
    color: '#FDE68A',
    intensity: 2.4,
    azimuth: -155,
    elevation: 52,
    distance: 7,
  },
  ambientIntensity: 0.45,
  ambientColor: '#E2E8F0',
  envIntensity: 1.15,
  exposure: 1.1,
  shadowsEnabled: true,
  shadowSoftness: 3,
  showLightHelpers: false,
  backgroundColor: '#0B0D11',
  showGrid: true,
  showAxes: false,
  autoRotate: false,
  autoRotateSpeed: 1.2,
};

export const COLOR_SWATCHES = [
  { name: 'Titanyum Gri', hex: '#B8C2CC' },
  { name: 'Kuvars Beyaz', hex: '#EAECEF' },
  { name: 'Saf Altın', hex: '#E5A93C' },
  { name: 'Saten Bakır', hex: '#D9734E' },
  { name: 'Kobalt Mavi', hex: '#2294E3' },
  { name: 'Zümrüt Yeşil', hex: '#10B981' },
  { name: 'Kızıl Alaşım', hex: '#EF4444' },
  { name: 'Obsidyen Siyah', hex: '#262B33' },
];
