import { LightingPreset, LightingSettings, MaterialPreset, MaterialSettings } from '../types/studio';

export interface CoreMaterialFinish {
  id: 'matte' | 'glossy' | 'transparent' | 'metallic';
  name: string;
  label: string;
  description: string;
  iconGradient: string;
  settings: Partial<MaterialSettings>;
}

export const CORE_MATERIAL_FINISHES: CoreMaterialFinish[] = [
  {
    id: 'matte',
    name: 'Mat',
    label: 'Mat Yüzey',
    description: 'Işık yansıtmayan pürüzsüz saten kaplama',
    iconGradient: 'linear-gradient(135deg, #64748b 0%, #334155 100%)',
    settings: {
      roughness: 0.88,
      metalness: 0.0,
      clearcoat: 0.0,
      clearcoatRoughness: 0.5,
      transmission: 0.0,
      opacity: 1.0,
      ior: 1.5,
      surfacePattern: 'none',
    },
  },
  {
    id: 'glossy',
    name: 'Parlak',
    label: 'Parlak Cilalı',
    description: 'Yüksek yansımalı berrak vernikli kaplama',
    iconGradient: 'linear-gradient(135deg, #f8fafc 0%, #94a3b8 50%, #475569 100%)',
    settings: {
      roughness: 0.08,
      metalness: 0.04,
      clearcoat: 0.85,
      clearcoatRoughness: 0.04,
      transmission: 0.0,
      opacity: 1.0,
      ior: 1.55,
      surfacePattern: 'none',
    },
  },
  {
    id: 'transparent',
    name: 'Şeffaf',
    label: 'Şeffaf Cam / Akrilik',
    description: 'Işık geçiren berrak cam ve kristal doku',
    iconGradient: 'linear-gradient(135deg, #e0f2fe 0%, #38bdf8 50%, #0369a1 100%)',
    settings: {
      roughness: 0.1,
      metalness: 0.02,
      clearcoat: 0.95,
      clearcoatRoughness: 0.05,
      transmission: 0.88,
      opacity: 0.9,
      ior: 1.52,
      surfacePattern: 'none',
    },
  },
  {
    id: 'metallic',
    name: 'Metalik',
    label: 'Metalik Krom',
    description: 'Ayna parlaklığında krom ve alaşım yansıma',
    iconGradient: 'linear-gradient(135deg, #fde68a 0%, #f59e0b 50%, #b45309 100%)',
    settings: {
      roughness: 0.2,
      metalness: 0.96,
      clearcoat: 0.25,
      clearcoatRoughness: 0.15,
      transmission: 0.0,
      opacity: 1.0,
      ior: 1.6,
      surfacePattern: 'none',
    },
  },
];

export const MATERIAL_PRESETS: MaterialPreset[] = [
  {
    id: 'matte_slate',
    name: 'Mat Saten Dokulu',
    category: 'Mat',
    swatchGradient: 'linear-gradient(135deg, #64748b 0%, #334155 100%)',
    settings: {
      color: '#475569',
      roughness: 0.88,
      metalness: 0.0,
      clearcoat: 0.0,
      clearcoatRoughness: 0.5,
      ior: 1.5,
      transmission: 0,
      opacity: 1,
      emissiveColor: '#000000',
      emissiveIntensity: 0,
      flatShading: false,
      doubleSided: true,
      surfacePattern: 'none',
      patternScale: 4,
      bumpScale: 0.015,
    },
  },
  {
    id: 'glossy_pure',
    name: 'Parlak Cilalı Vernik',
    category: 'Parlak',
    swatchGradient: 'linear-gradient(135deg, #f8fafc 0%, #94a3b8 50%, #475569 100%)',
    settings: {
      color: '#E2E8F0',
      roughness: 0.08,
      metalness: 0.04,
      clearcoat: 0.85,
      clearcoatRoughness: 0.04,
      ior: 1.55,
      transmission: 0,
      opacity: 1,
      emissiveColor: '#000000',
      emissiveIntensity: 0,
      flatShading: false,
      doubleSided: true,
      surfacePattern: 'none',
      patternScale: 4,
      bumpScale: 0.015,
    },
  },
  {
    id: 'glass_crystal',
    name: 'Şeffaf Kristal Cam',
    category: 'Şeffaf',
    swatchGradient: 'linear-gradient(135deg, #e0f2fe 0%, #7dd3fc 50%, #0369a1 100%)',
    settings: {
      color: '#D8F3FF',
      roughness: 0.1,
      metalness: 0.02,
      clearcoat: 0.95,
      clearcoatRoughness: 0.05,
      ior: 1.52,
      transmission: 0.88,
      opacity: 0.9,
      emissiveColor: '#000000',
      emissiveIntensity: 0,
      flatShading: false,
      doubleSided: true,
      surfacePattern: 'none',
      patternScale: 4,
      bumpScale: 0,
    },
  },
  {
    id: 'anodized_gold',
    name: 'Metalik Anodize Altın',
    category: 'Metalik',
    swatchGradient: 'linear-gradient(135deg, #fde68a 0%, #f59e0b 55%, #92400e 100%)',
    settings: {
      color: '#E5A93C',
      roughness: 0.2,
      metalness: 0.96,
      clearcoat: 0.3,
      clearcoatRoughness: 0.12,
      ior: 1.6,
      transmission: 0,
      opacity: 1,
      emissiveColor: '#000000',
      emissiveIntensity: 0,
      flatShading: false,
      doubleSided: true,
      surfacePattern: 'none',
      patternScale: 4,
      bumpScale: 0.015,
    },
  },
  {
    id: 'brushed_titanium',
    name: 'Fırçalanmış Titanyum',
    category: 'Metalik',
    swatchGradient: 'linear-gradient(135deg, #cbd5e1 0%, #64748b 50%, #334155 100%)',
    settings: {
      color: '#B8C2CC',
      roughness: 0.28,
      metalness: 0.92,
      clearcoat: 0.15,
      clearcoatRoughness: 0.25,
      ior: 1.5,
      transmission: 0,
      opacity: 1,
      emissiveColor: '#000000',
      emissiveIntensity: 0,
      flatShading: false,
      doubleSided: true,
      surfacePattern: 'brushed_metal',
      patternScale: 4,
      bumpScale: 0.025,
    },
  },
  {
    id: 'automotive_carbon',
    name: 'Karbon Fiber Dokuma',
    category: 'Kompozit',
    swatchGradient: 'linear-gradient(135deg, #475569 0%, #1e293b 50%, #0f172a 100%)',
    settings: {
      color: '#262B33',
      roughness: 0.24,
      metalness: 0.45,
      clearcoat: 0.92,
      clearcoatRoughness: 0.08,
      ior: 1.58,
      transmission: 0,
      opacity: 1,
      emissiveColor: '#000000',
      emissiveIntensity: 0,
      flatShading: false,
      doubleSided: true,
      surfacePattern: 'carbon_weave',
      patternScale: 6,
      bumpScale: 0.04,
    },
  },
];

export const COLOR_SWATCHES = [
  { name: 'Obsidyen Siyah', hex: '#181A20' },
  { name: 'Titanyum Gri', hex: '#94A3B8' },
  { name: 'Saf Beyaz', hex: '#F8FAFC' },
  { name: 'Kehribar Altın', hex: '#F59E0B' },
  { name: 'Bakır Bronz', hex: '#EA580C' },
  { name: 'Yakut Kırmızı', hex: '#E11D48' },
  { name: 'Safir Mavi', hex: '#2563EB' },
  { name: 'Zümrüt Yeşil', hex: '#059669' },
  { name: 'Gökyüzü Mavisi', hex: '#38BDF8' },
  { name: 'Sıcak Bej', hex: '#D4B996' },
];

export const DEFAULT_MATERIAL_SETTINGS: MaterialSettings = {
  useOriginalMaterials: true,
  presetId: 'original',
  wireframe: false,
  ...MATERIAL_PRESETS[0].settings,
};

export const LIGHTING_PRESETS: LightingPreset[] = [
  {
    id: 'studio_three_point',
    name: 'Üç Noktalı Ürün Stüdyosu',
    description: 'Dengeli ana ışık, soğuk dolgu ve keskin kontur aydınlatması',
    settings: {
      keyLight: {
        enabled: true,
        color: '#FFF7ED',
        intensity: 2.8,
        azimuth: 42,
        elevation: 48,
        distance: 7,
        castShadow: true,
      },
      fillLight: {
        enabled: true,
        color: '#93C5FD',
        intensity: 1.35,
        azimuth: -55,
        elevation: 28,
        distance: 7,
      },
      rimLight: {
        enabled: true,
        color: '#FDE68A',
        intensity: 2.4,
        azimuth: -155,
        elevation: 52,
        distance: 7,
      },
      ambientIntensity: 0.45,
      ambientColor: '#E2E8F0',
      envIntensity: 1.15,
      exposure: 1.1,
      backgroundColor: '#0B0D11',
    },
  },
  {
    id: 'golden_hour',
    name: 'Sıcak Altın Saat',
    description: 'Kehribar ana ışık ve derin atmosferik kontrast',
    settings: {
      keyLight: {
        enabled: true,
        color: '#FDBA74',
        intensity: 3.4,
        azimuth: 65,
        elevation: 24,
        distance: 7,
        castShadow: true,
      },
      fillLight: {
        enabled: true,
        color: '#6366F1',
        intensity: 0.9,
        azimuth: -70,
        elevation: 35,
        distance: 7,
      },
      rimLight: {
        enabled: true,
        color: '#FEF08A',
        intensity: 3.1,
        azimuth: -130,
        elevation: 30,
        distance: 7,
      },
      ambientIntensity: 0.35,
      ambientColor: '#FED7AA',
      envIntensity: 1.0,
      exposure: 1.15,
      backgroundColor: '#12100E',
    },
  },
  {
    id: 'technical_lab',
    name: 'Endüstriyel CAD Laboratuvarı',
    description: 'Yüksek netlikli nötr beyaz mühendislik inceleme ışığı',
    settings: {
      keyLight: {
        enabled: true,
        color: '#FFFFFF',
        intensity: 2.6,
        azimuth: 35,
        elevation: 60,
        distance: 7,
        castShadow: true,
      },
      fillLight: {
        enabled: true,
        color: '#E0F2FE',
        intensity: 1.8,
        azimuth: -45,
        elevation: 45,
        distance: 7,
      },
      rimLight: {
        enabled: true,
        color: '#38BDF8',
        intensity: 2.2,
        azimuth: 170,
        elevation: 50,
        distance: 7,
      },
      ambientIntensity: 0.65,
      ambientColor: '#F8FAFC',
      envIntensity: 1.4,
      exposure: 1.2,
      backgroundColor: '#0F141C',
    },
  },
  {
    id: 'dramatic_rim',
    name: 'Dramatik Kontur & Silüet',
    description: 'Düşük dolgu ışığı ve keskin kenar vurguları',
    settings: {
      keyLight: {
        enabled: true,
        color: '#F8FAFC',
        intensity: 2.1,
        azimuth: 25,
        elevation: 35,
        distance: 7,
        castShadow: true,
      },
      fillLight: {
        enabled: true,
        color: '#334155',
        intensity: 0.4,
        azimuth: -60,
        elevation: 20,
        distance: 7,
      },
      rimLight: {
        enabled: true,
        color: '#F59E0B',
        intensity: 4.2,
        azimuth: -165,
        elevation: 42,
        distance: 7,
      },
      ambientIntensity: 0.2,
      ambientColor: '#94A3B8',
      envIntensity: 0.85,
      exposure: 1.0,
      backgroundColor: '#07080A',
    },
  },
];

export const DEFAULT_LIGHTING_SETTINGS: LightingSettings = {
  presetId: 'studio_three_point',
  keyLight: {
    enabled: true,
    color: '#FFF7ED',
    intensity: 2.8,
    azimuth: 42,
    elevation: 48,
    distance: 7,
    castShadow: true,
  },
  fillLight: {
    enabled: true,
    color: '#93C5FD',
    intensity: 1.35,
    azimuth: -55,
    elevation: 28,
    distance: 7,
  },
  rimLight: {
    enabled: true,
    color: '#FDE68A',
    intensity: 2.4,
    azimuth: -155,
    elevation: 52,
    distance: 7,
  },
  ambientIntensity: 0.45,
  ambientColor: '#E2E8F0',
  envIntensity: 1.15,
  exposure: 1.1,
  shadowsEnabled: true,
  shadowSoftness: 3,
  showLightHelpers: false,
  backgroundColor: '#0B0D11',
  showGrid: true,
  showAxes: false,
  autoRotate: false,
  autoRotateSpeed: 1.2,
};
